### ISSUE TITLE
Comments on http://standardhealthrecord.org/cimpl-doc/cimpl6ObjectiveFHIR/#class-hierarchy

### ISSUE THREAD

**Issue by saulakravitz** [standardhealth/cimpl-doc#9]
Coverage:  would be nice if there was a link to the resources that ARE covered by OBF.

OBF Actors:   SubjectOfRecord alludes to FocalSubject, but FocalSubject alludes to "person of record"...is that SubjectOfRecord?  

Class Hierarchy:   The link to OBF model documentation ( http://standardhealthrecord.org/cimpl-doc/cimpl6ObjectiveFHIR/#model-documentation) is non-functional.     At a glance I can't figure out whether MedicationKnowledge and List are included.

Subclassing:  "obviously defines the parent class" -- I suggest dropping 'obviously', since it comes off as condescending.

**Comment by markkramerus** [comment]
https://standardhealthrecord.atlassian.net/browse/CIMPL-47
